### PR TITLE
Temp spike battery improvements

### PR DESCRIPTION
**Pull request by h3ss**
I finally managed to capture readings from an entire discharge cycle of a TempSpike battery.  The battery reading sent by the device appears to be a reading in millivolts, and the discharge cycle is a non-linear function as you would expect in that situation.

To create a more accurate mapping of voltage to battery percentage, I used some machine learning to optimize a function in the form `A*tanh(B*x+C)+D` where A->D are variables that were optimized with TensorFlow.  (I chose that function format simply because I noticed that the curve from the readings looked fairly similar to a `tanh` curve).  This yielded a function whose output fit within about 1.8% of the actual data collected, which I think is good enough ;)

I also added clamping for _both_ minimum and maximum values, just in case.

### CODE REVIEW

**Comment by h3ss** [comment]
imgpsh_fullsize_anim (5)
Battery curve comparison:
- Blue line are device readings
- Orange line is the predicted value

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
Thanks.  Release will publish shortly

**Comment by bdraco** [comment]
I'm not at my desk, so it'd be great if you could take care of bumping library in HA as well

**Comment by bdraco** [comment]
I forgot to fix the commit message name so the release failed, I'll have to wait till I get back to my desk to do it manually

**Comment by bdraco** [comment]
all sorted https://github.com/Bluetooth-Devices/thermopro-ble/releases/tag/v0.9.0 published

**Comment by h3ss** [comment]
Thank you very much @bdraco !

> I'm not at my desk, so it'd be great if you could take care of bumping library in HA as well

I went ahead and submitted this.  My first time doing a PR to that repo so hope I got it right :)

**Pull request merged**
