### PR TITLE
feat: add support for TP357S

### PR DESCRIPTION
**Pull request by yoxcu**
added TP357S support as in 
https://github.com/custom-components/ble_monitor/pull/1240/commits/dbe8d099b383b2c36c9182da01113de84a506a0f

the new S version returns 2 bytes more

### CODE REVIEW

**Review by bdraco — CHANGES_REQUESTED** [review]
Please add a test for the new model

**Comment by bdraco** [comment]
You should be able to mostly copy https://github.com/Bluetooth-Devices/thermopro-ble/blob/3c78e2f776a666bc47b05689f083054050d49e40/tests/test_parser.py#L18

- change the manufacturer_data

copy https://github.com/Bluetooth-Devices/thermopro-ble/blob/3c78e2f776a666bc47b05689f083054050d49e40/tests/test_parser.py#L110

- update the values

**Comment by NicholasBM** [comment]
Hello

Thanks for your reply. I was not clear on the workflow, as I could see some
checks were not successful, calling out a CI / Lint issue which seemed
simple, but now I see you also asked for tests

**Comment by bdraco** [comment]
The tests are pretty trivial to write if you have the advertisement data from one of these devices, but without it there is no way to help the op get this over the finish line

**Comment by NicholasBM** [comment]
Here is the advertisement data from my TP357S device, does this help

Device Address : D8:A4:2A:A1:26:73
Raw Data : 02 01 06 0E 08 54 50 33 35 37 53 20 28 32 36 37 33 29 08 FF C2
B3 00 24 22 0B 01

**Comment by bdraco** [comment]
If you turn on debug logging for the bluetooth integration or manually via
https://www.home-assistant.io/integrations/logger/

```
# Example configuration.yaml entry
logger:
  default: info
  logs:
    homeassistant.components.bluetooth: debug
```

You should be able to get it to log the parsed advertisement data  that can be used to write the test

**Comment by naduweisstschon** [comment]
Let me supply the advertisement data of two different sensors from the HA debug log:

```
2023-12-01 13:02:33.123 DEBUG (MainThread) [homeassistant.components.bluetooth.manager] hci0 ([redacted]) [connectable]: [redacted] AdvertisementData(local_name='TP357S ([redacted])', manufacturer_data={59074: b'\x00\'"\x0b\x01', 59330: b'\x00\'"\x0b\x01', 59586: b'\x00\'"\x0b\x01', 59842: b'\x00\'"\x0b\x01', 61890: b'\x00\'"\x0b\x01', 62914: b'\x00\'"\x0b\x01', 63170: b'\x00)"\x0b\x01', 62658: b'\x00\'"\x0b\x01', 62402: b'\x00\'"\x0b\x01', 62146: b'\x00\'"\x0b\x01', 61378: b'\x00\'"\x0b\x01', 61122: b'\x00\'"\x0b\x01', 60866: b'\x00\'"\x0b\x01', 60610: b'\x00\'"\x0b\x01', 60354: b'\x00\'"\x0b\x01', 60098: b'\x00\'"\x0b\x01', 58818: b'\x00\'"\x0b\x01', 58562: b'\x00("\x0b\x01', 61634: b'\x00\'"\x0b\x01', 58306: b'\x00("\x0b\x01', 58050: b'\x00("\x0b\x01', 57794: b'\x00)"\x0b\x01', 57538: b'\x00)"\x0b\x01', 57282: b'\x00)"\x0b\x01', 57026: b'\x00)"\x0b\x01', 56770: b'\x00)"\x0b\x01', 56514: b'\x00*"\x0b\x01', 56258: b'\x00*"\x0b\x01', 56002: b'\x00*"\x0b\x01', 55746: b'\x00*"\x0b\x01', 55490: b'\x00*"\x0b\x01', 55234: b'\x00*"\x0b\x01', 54978: b'\x00)"\x0b\x01', 54722: b'\x00)"\x0b\x01', 54466: b'\x00("\x0b\x01', 54210: b'\x00("\x0b\x01', 53954: b'\x00\'"\x0b\x01', 53698: b'\x00\'"\x0b\x01', 53442: b'\x00\'"\x0b\x01', 53186: b'\x00&"\x0b\x01', 52930: b'\x00&"\x0b\x01', 52674: b'\x00&"\x0b\x01', 52418: b'\x00%"\x0b\x01', 65474: b'\xff\xff"\x0b\x01'}, rssi=-61) match: set()
2023-12-01 13:04:01.441 DEBUG (MainThread) [homeassistant.components.bluetooth.manager] hci0 ([redacted]) [connectable]: [redacted] AdvertisementData(local_name='TP357S ([redacted])', manufacturer_data={61122: b'\x00)"\x0b\x01', 60866: b'\x00)"\x0b\x01', 60610: b'\x00)"\x0b\x01', 60354: b'\x00("\x0b\x01', 60098: b'\x00("\x0b\x01', 59842: b'\x00)"\x0b\x01', 59586: b'\x00("\x0b\x01', 59330: b'\x00("\x0b\x01', 59074: b'\x00("\x0b\x01', 58818: b'\x00("\x0b\x01', 58562: b'\x00\'"\x0b\x01', 58306: b'\x00("\x0b\x01', 58050: b'\x00("\x0b\x01', 57794: b'\x00)"\x0b\x01', 57538: b'\x00)"\x0b\x01', 57282: b'\x00)"\x0b\x01', 57026: b'\x00)"\x0b\x01', 56770: b'\x00)"\x0b\x01', 56514: b'\x00)"\x0b\x01', 56258: b'\x00)"\x0b\x01', 56002: b'\x00)"\x0b\x01', 55746: b'\x00*"\x0b\x01', 55490: b'\x00)"\x0b\x01', 55234: b'\x00*"\x0b\x01', 54978: b'\x00*"\x0b\x01', 54722: b'\x00*"\x0b\x01', 54466: b'\x00+"\x0b\x01', 54210: b'\x00-"\x0b\x01', 53954: b'\x00,"\x0b\x01', 53698: b'\x00/"\x0b\x01', 53442: b'\x001"\x0b\x01', 53186: b'\x00."\x0b\x01', 52930: b'\x00,"\x0b\x01', 52674: b'\x00,"\x0b\x01', 52418: b'\x00+"\x0b\x01', 52162: b'\x00*"\x0b\x01', 51906: b'\x00*"\x0b\x01', 51650: b'\x00*"\x0b\x01', 51394: b'\x00*"\x0b\x01', 51138: b'\x00*"\x0b\x01', 50882: b'\x00)"\x0b\x01'}, rssi=-62) match: set()
```

Hope that helps! Unfortunately, I don't have the time to look into it myself.

**Comment by bdraco** [comment]
released as https://pypi.org/project/thermopro-ble/0.5.0/ if someone wants to update Home Assistant

**Pull request closed without merging**
